#ifndef opacity_h
#define opacity_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace opacity_core {
#endif  // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern const int32_t OPACITY_OK;

extern const int32_t OPACITY_MISSING_POINTER;

extern const int32_t OPACITY_GENERIC_ERROR;

extern const int32_t OPACITY_NOT_SUPPORTED;

extern const int32_t OPACITY_ENVIRONMENT_TEST;

extern const int32_t OPACITY_ENVIRONMENT_LOCAL;

extern const int32_t OPACITY_ENVIRONMENT_STAGING;

extern const int32_t OPACITY_ENVIRONMENT_PRODUCTION;

int32_t init(const char *api_key_str,
             bool dry_run,
             int32_t backend_environment,
             bool show_errors_in_webview);

int32_t get(const char *name, const char *params, char **res_ptr, char **err_ptr);

void free_string(char *ptr);

void emit_webview_event(const char *payload);

extern const char *get_ip_address(void);

extern void secure_set(const char *key, const char *value);

extern const char *secure_get(const char *key);

extern void android_prepare_request(const char *_url);

extern void android_set_request_header(const char *_key, const char *_value);

extern void android_present_webview(void);

extern void android_close_webview(void);

extern void ios_prepare_request(const char *url);

extern void ios_set_request_header(const char *key, const char *value);

extern void ios_present_webview(void);

extern void ios_close_webview(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace opacity_core
#endif  // __cplusplus

#endif  /* opacity_h */
