name: XCUITest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  xcuitest:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install dependencies (if needed)
        run: cd pod_example && pod install # or `swift package resolve` if using SPM

      - name: Run UI Tests
        run: |
          xcodebuild test \
            -workspace pod_example/OpacityPod.xcworkspace \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -scheme OpacityPod_Example \
            -only-testing:OpacityPod_UITests
