name: XCUITest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  xcuitest:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install dependencies (if needed)
        run: pod install # or `swift package resolve` if using SPM
        working-directory: YourProject

      - name: Run UI Tests
        run: |
          xcodebuild test \
            -workspace YourProject.xcworkspace \  # Use .xcworkspace if using CocoaPods
            -scheme YourScheme \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -only-testing:YourUITests
